service: app

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /hello
          method: get
    layers:
      - arn:aws:lambda:us-east-1:201807860611:layer:PrivateModules:4